name: MSBuild MSVC Project File CI

on: [push, pull_request]

env:
  SOLUTION_FILE_PATH: ./msvc/portaudio.sln
  VCPROJ_FILE_PATH: ./msvc/portaudio.vcproj
  VCXPROJ_FILE_PATH: ./msvc/portaudio.vcxproj
  VCXPROJ_FILTERS_FILE_PATH: ./msvc/portaudio.vcxproj.filters
  VCXPROJ_USER_FILE_PATH: ./msvc/portaudio.vcxproj.user
  DEF_FILE_PATH: ./msvc/portaudio.def
  BUILD_OUTPUT_DIR: ./build_output

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - uses: actions/checkout@v2

    - name: Upgrade VC Project File
      run: |
        $devenv = & vswhere.exe '-property' productPath
        & $devenv "${{env.VCPROJ_FILE_PATH}}" /Upgrade /NoSplash | Out-Null
        while (!(Test-Path "${{env.VCXPROJ_FILE_PATH}}")) { Start-Sleep -Seconds 10 }
        while (!(Test-Path "${{env.VCXPROJ_FILTERS_FILE_PATH}}")) { Start-Sleep -Seconds 10 }
        Start-Sleep -Seconds 5

    - name: Remove ASIO Files and Enable PA_USE_DS=1
      run: |
        $xdoc = New-Object System.Xml.XmlDocument
        $vcxprojFile = Resolve-Path "${{env.VCXPROJ_FILE_PATH}}"
        $xdoc.Load($vcxprojFile)
        $ns = New-Object Xml.XmlNamespaceManager($xdoc.NameTable)
        $ns.AddNamespace("vs", $xdoc.DocumentElement.NamespaceURI)

        # Remove ASIO sources
        $nodes = $xdoc.SelectNodes("//vs:ClCompile[contains(@Include, '..\src\hostapi\asio')]", $ns)
        ForEach ($node in $nodes) { $node.ParentNode.RemoveChild($node) }

        # Enable DirectSound
        $defs = $xdoc.SelectNodes("//vs:PreprocessorDefinitions[contains(., 'PA_USE_DS=0')]", $ns)
        ForEach ($def in $defs) { $def.InnerText = $def.InnerText -replace 'PA_USE_DS=0', 'PA_USE_DS=1' }

        $xdoc.Save($vcxprojFile)

        # Remove ASIO nodes from .vcxproj.filters
        $vcxprojFiltersFile = Resolve-Path "${{env.VCXPROJ_FILTERS_FILE_PATH}}"
        $xdoc.Load($vcxprojFiltersFile)
        $ns = New-Object Xml.XmlNamespaceManager($xdoc.NameTable)
        $ns.AddNamespace("vs", $xdoc.DocumentElement.NamespaceURI)
        $nodes = $xdoc.SelectNodes("//vs:ClCompile[contains(@Include, '..\src\hostapi\asio')]", $ns)
        ForEach ($node in $nodes) { $node.ParentNode.RemoveChild($node) }
        $nodes = $xdoc.SelectNodes("//vs:ClInclude[contains(@Include, 'pa_asio.h')]", $ns)
        ForEach ($node in $nodes) { $node.ParentNode.RemoveChild($node) }
        $xdoc.Save($vcxprojFiltersFile)

        # Remove PaAsio_ symbols from .def
        Set-Content -Path "${{env.DEF_FILE_PATH}}" -Value (Get-Content -Path "${{env.DEF_FILE_PATH}}" | Select-String -Pattern 'PaAsio_' -NotMatch)

    - name: Build x64 Release with Static VC Runtime
      run: |
        msbuild /m `
          /p:Configuration=Release `
          /p:Platform=x64 `
          /p:RuntimeLibrary=MultiThreaded `
          /p:OutDir=${{env.BUILD_OUTPUT_DIR}}\ `
          ${{env.VCXPROJ_FILE_PATH}}

    - name: Create ZIP of DLL and LIB
      run: |
        $dllPath = "${{env.BUILD_OUTPUT_DIR}}\portaudio.dll"
        $libPath = "${{env.BUILD_OUTPUT_DIR}}\portaudio.lib"
        $zipPath = "${{github.workspace}}\portaudio-x64-release.zip"
        if (Test-Path $zipPath) { Remove-Item $zipPath }
        Compress-Archive -Path $dllPath,$libPath -DestinationPath $zipPath
        Write-Output "ZIP created at $zipPath"

    - name: Upload ZIP Artifact
      uses: actions/upload-artifact@v4
      with:
        name: portaudio-x64-release
        path: portaudio-x64-release.zip
